INFO:aiogram:Bot: СЛИФФКИ БОТ [@sliffkifans_bot]
INFO:aiogram.dispatcher.dispatcher:Start polling.
INFO:root:new luder: 1882355196
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-15' coro=<Dispatcher._process_polling_updates() done, defined at /home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:409> exception=TypeError("'NoneType' object is not subscriptable")>
Traceback (most recent call last):
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 417, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 238, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 259, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/nail/oir/actual.py", line 50, in main
    link = link[0]
TypeError: 'NoneType' object is not subscriptable
INFO:aiogram.dispatcher.dispatcher:Stop polling...
WARNING:aiogram:Goodbye!
INFO:aiogram:Bot: СЛИФФКИ БОТ [@sliffkifans_bot]
INFO:aiogram.dispatcher.dispatcher:Start polling.
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-7' coro=<Dispatcher._process_polling_updates() done, defined at /home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:409> exception=SyntaxError('syntax error at or near "VALUES1882355196"\nLINE 1: INSERT INTO users(userid)VALUES1882355196;\n                                 ^\n')>
Traceback (most recent call last):
  File "/home/nail/oir/actual.py", line 35, in welcome
    cursor.execute(f"INSERT INTO users(userid,username)VALUES{valua};")
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "users_userid_key"
DETAIL:  Key (userid)=(1882355196) already exists.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 417, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 238, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 259, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/nail/oir/actual.py", line 38, in welcome
    cursor.execute(f"INSERT INTO users(userid)VALUES{message.from_user.id};")
psycopg2.errors.SyntaxError: syntax error at or near "VALUES1882355196"
LINE 1: INSERT INTO users(userid)VALUES1882355196;
                                 ^

ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-10' coro=<Dispatcher._process_polling_updates() done, defined at /home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:409> exception=SyntaxError('syntax error at or near "VALUES1882355196"\nLINE 1: INSERT INTO users(userid)VALUES1882355196;\n                                 ^\n')>
Traceback (most recent call last):
  File "/home/nail/oir/actual.py", line 35, in welcome
    cursor.execute(f"INSERT INTO users(userid,username)VALUES{valua};")
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "users_userid_key"
DETAIL:  Key (userid)=(1882355196) already exists.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 417, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 238, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 259, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/nail/oir/actual.py", line 38, in welcome
    cursor.execute(f"INSERT INTO users(userid)VALUES{message.from_user.id};")
psycopg2.errors.SyntaxError: syntax error at or near "VALUES1882355196"
LINE 1: INSERT INTO users(userid)VALUES1882355196;
                                 ^

ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-13' coro=<Dispatcher._process_polling_updates() done, defined at /home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:409> exception=TypeError("'NoneType' object is not subscriptable")>
Traceback (most recent call last):
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 417, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 238, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 259, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/nail/oir/actual.py", line 52, in main
    link = link[0]
TypeError: 'NoneType' object is not subscriptable
INFO:aiogram.dispatcher.dispatcher:Stop polling...
WARNING:aiogram:Goodbye!
INFO:aiogram:Bot: СЛИФФКИ БОТ [@sliffkifans_bot]
INFO:aiogram.dispatcher.dispatcher:Start polling.
INFO:root:new luder: 1882355196
INFO:aiogram.dispatcher.dispatcher:Stop polling...
WARNING:aiogram:Goodbye!
INFO:aiogram:Bot: СЛИФФКИ БОТ [@sliffkifans_bot]
INFO:aiogram.dispatcher.dispatcher:Start polling.
INFO:root:new luder: 1882355196
INFO:aiogram:Bot: СЛИФФКИ БОТ [@sliffkifans_bot]
INFO:aiogram.dispatcher.dispatcher:Start polling.
INFO:root:new luder: 1882355196
INFO:aiogram.dispatcher.dispatcher:Stop polling...
WARNING:aiogram:Goodbye!
INFO:aiogram:Bot: СЛИФФКИ БОТ [@sliffkifans_bot]
INFO:aiogram.dispatcher.dispatcher:Start polling.
INFO:root:new luder: 1882355196
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-17' coro=<Dispatcher._process_polling_updates() done, defined at /home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:409> exception=SyntaxError('syntax error at or near "*"\nLINE 1: UPDATE actual SET link = d WHERE userid = *;\n                                                  ^\n')>
Traceback (most recent call last):
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 417, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 238, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 259, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/nail/oir/actual.py", line 58, in add
    cursor.execute(f'UPDATE actual SET link = {linked} WHERE userid = *;')
psycopg2.errors.SyntaxError: syntax error at or near "*"
LINE 1: UPDATE actual SET link = d WHERE userid = *;
                                                  ^

INFO:aiogram.dispatcher.dispatcher:Stop polling...
WARNING:aiogram:Goodbye!
INFO:aiogram:Bot: СЛИФФКИ БОТ [@sliffkifans_bot]
INFO:aiogram.dispatcher.dispatcher:Start polling.
INFO:root:new luder: 1882355196
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-17' coro=<Dispatcher._process_polling_updates() done, defined at /home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:409> exception=SyntaxError('syntax error at or near "*"\nLINE 1: UPDATE actual SET link = d WHERE userid = *;\n                                                  ^\n')>
Traceback (most recent call last):
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 417, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 238, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 259, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/nail/oir/actual.py", line 58, in add
    cursor.execute(f'UPDATE actual SET link = {linked} WHERE userid = *;')
psycopg2.errors.SyntaxError: syntax error at or near "*"
LINE 1: UPDATE actual SET link = d WHERE userid = *;
                                                  ^

INFO:aiogram.dispatcher.dispatcher:Stop polling...
WARNING:aiogram:Goodbye!
INFO:aiogram:Bot: СЛИФФКИ БОТ [@sliffkifans_bot]
INFO:aiogram.dispatcher.dispatcher:Start polling.
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-7' coro=<Dispatcher._process_polling_updates() done, defined at /home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:409> exception=SyntaxError('syntax error at or near "*"\nLINE 1: UPDATE actual SET link = d WHERE userid = *;\n                                                  ^\n')>
Traceback (most recent call last):
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 417, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 238, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 259, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/nail/oir/actual.py", line 59, in add
    cursor.execute(f'UPDATE actual SET link = {linked} WHERE userid = *;')
psycopg2.errors.SyntaxError: syntax error at or near "*"
LINE 1: UPDATE actual SET link = d WHERE userid = *;
                                                  ^

INFO:aiogram.dispatcher.dispatcher:Stop polling...
WARNING:aiogram:Goodbye!
INFO:aiogram:Bot: СЛИФФКИ БОТ [@sliffkifans_bot]
INFO:aiogram.dispatcher.dispatcher:Start polling.
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-7' coro=<Dispatcher._process_polling_updates() done, defined at /home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:409> exception=SyntaxError('syntax error at or near "*"\nLINE 1: UPDATE actual SET link = sliffki1 WHERE userid = *;\n                                                         ^\n')>
Traceback (most recent call last):
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 417, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 238, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 259, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/nail/oir/actual.py", line 60, in add
    cursor.execute(f'UPDATE actual SET link = {linked} WHERE userid = *;')
psycopg2.errors.SyntaxError: syntax error at or near "*"
LINE 1: UPDATE actual SET link = sliffki1 WHERE userid = *;
                                                         ^

INFO:aiogram.dispatcher.dispatcher:Stop polling...
WARNING:aiogram:Goodbye!
INFO:aiogram:Bot: СЛИФФКИ БОТ [@sliffkifans_bot]
INFO:aiogram.dispatcher.dispatcher:Start polling.
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-7' coro=<Dispatcher._process_polling_updates() done, defined at /home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:409> exception=UndefinedColumn('column "sliffki1" does not exist\nLINE 1: UPDATE actual SET link = sliffki1\n                                 ^\n')>
Traceback (most recent call last):
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 417, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 238, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 259, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/nail/oir/actual.py", line 60, in add
    cursor.execute(f'UPDATE actual SET link = {linked}')
psycopg2.errors.UndefinedColumn: column "sliffki1" does not exist
LINE 1: UPDATE actual SET link = sliffki1
                                 ^

INFO:aiogram.dispatcher.dispatcher:Stop polling...
WARNING:aiogram:Goodbye!
INFO:aiogram:Bot: СЛИФФКИ БОТ [@sliffkifans_bot]
INFO:aiogram.dispatcher.dispatcher:Start polling.
INFO:root:new luder: 1882355196
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-17' coro=<Dispatcher._process_polling_updates() done, defined at /home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:409> exception=UndefinedColumn('column "sliffki1" does not exist\nLINE 1: UPDATE actual SET link = sliffki1\n                                 ^\n')>
Traceback (most recent call last):
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 417, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 238, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 259, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/nail/oir/actual.py", line 60, in add
    cursor.execute(f'UPDATE actual SET link = {linked}')
psycopg2.errors.UndefinedColumn: column "sliffki1" does not exist
LINE 1: UPDATE actual SET link = sliffki1
                                 ^

INFO:root:new luder: 1882355196
INFO:aiogram.dispatcher.dispatcher:Stop polling...
WARNING:aiogram:Goodbye!
INFO:aiogram:Bot: СЛИФФКИ БОТ [@sliffkifans_bot]
INFO:aiogram.dispatcher.dispatcher:Start polling.
INFO:root:new luder: 1882355196
INFO:aiogram.dispatcher.dispatcher:Stop polling...
WARNING:aiogram:Goodbye!
INFO:aiogram:Bot: СЛИФФКИ БОТ [@sliffkifans_bot]
INFO:aiogram.dispatcher.dispatcher:Start polling.
INFO:aiogram.dispatcher.dispatcher:Stop polling...
WARNING:aiogram:Goodbye!
INFO:aiogram:Bot: СЛИФФКИ БОТ [@sliffkifans_bot]
INFO:aiogram.dispatcher.dispatcher:Start polling.
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-7' coro=<Dispatcher._process_polling_updates() done, defined at /home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:409> exception=SyntaxError('syntax error at or near "*"\nLINE 1: UPDATE actual SET link = sliffki1 WHERE *\n                                                ^\n')>
Traceback (most recent call last):
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 417, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 238, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 259, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/nail/oir/actual.py", line 62, in add
    cursor.execute(f'UPDATE actual SET link = {linked} WHERE *')
psycopg2.errors.SyntaxError: syntax error at or near "*"
LINE 1: UPDATE actual SET link = sliffki1 WHERE *
                                                ^

INFO:aiogram.dispatcher.dispatcher:Stop polling...
WARNING:aiogram:Goodbye!
INFO:aiogram:Bot: СЛИФФКИ БОТ [@sliffkifans_bot]
INFO:aiogram.dispatcher.dispatcher:Start polling.
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-7' coro=<Dispatcher._process_polling_updates() done, defined at /home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:409> exception=SyntaxError('syntax error at or near "*"\nLINE 1: UPDATE actual SET link = sliffki1 WHERE userid = *\n                                                         ^\n')>
Traceback (most recent call last):
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 417, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 238, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 259, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/nail/oir/actual.py", line 62, in add
    cursor.execute(f'UPDATE actual SET link = {linked} WHERE userid = *')
psycopg2.errors.SyntaxError: syntax error at or near "*"
LINE 1: UPDATE actual SET link = sliffki1 WHERE userid = *
                                                         ^

INFO:aiogram.dispatcher.dispatcher:Stop polling...
WARNING:aiogram:Goodbye!
INFO:aiogram:Bot: СЛИФФКИ БОТ [@sliffkifans_bot]
INFO:aiogram.dispatcher.dispatcher:Start polling.
INFO:root:new luder: 1882355196
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-12' coro=<Dispatcher._process_polling_updates() done, defined at /home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:409> exception=UndefinedColumn('column "sliffki1" does not exist\nLINE 1: UPDATE actual SET link = sliffki1;\n                                 ^\n')>
Traceback (most recent call last):
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 417, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 238, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 259, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/nail/oir/actual.py", line 62, in add
    cursor.execute(f'UPDATE actual SET link = {linked};')
psycopg2.errors.UndefinedColumn: column "sliffki1" does not exist
LINE 1: UPDATE actual SET link = sliffki1;
                                 ^

INFO:aiogram.dispatcher.dispatcher:Stop polling...
WARNING:aiogram:Goodbye!
INFO:aiogram:Bot: СЛИФФКИ БОТ [@sliffkifans_bot]
INFO:aiogram.dispatcher.dispatcher:Start polling.
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-7' coro=<Dispatcher._process_polling_updates() done, defined at /home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:409> exception=UndefinedColumn('column "sliffki1" does not exist\nLINE 1: UPDATE actual SET link = "sliffki1"\n                                 ^\n')>
Traceback (most recent call last):
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 417, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 238, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 259, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/nail/oir/actual.py", line 62, in add
    cursor.execute(f'UPDATE actual SET link = "{linked}"')
psycopg2.errors.UndefinedColumn: column "sliffki1" does not exist
LINE 1: UPDATE actual SET link = "sliffki1"
                                 ^

INFO:aiogram.dispatcher.dispatcher:Stop polling...
WARNING:aiogram:Goodbye!
INFO:aiogram:Bot: СЛИФФКИ БОТ [@sliffkifans_bot]
INFO:aiogram.dispatcher.dispatcher:Start polling.
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-7' coro=<Dispatcher._process_polling_updates() done, defined at /home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:409> exception=UndefinedColumn('column "sliffki1" does not exist\nLINE 1: UPDATE actual SET link = "sliffki1" WHERE id > 0\n                                 ^\n')>
Traceback (most recent call last):
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 417, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 238, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 259, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/nail/oir/actual.py", line 62, in add
    cursor.execute(f'UPDATE actual SET link = "{linked}" WHERE id > 0')
psycopg2.errors.UndefinedColumn: column "sliffki1" does not exist
LINE 1: UPDATE actual SET link = "sliffki1" WHERE id > 0
                                 ^

INFO:aiogram.dispatcher.dispatcher:Stop polling...
WARNING:aiogram:Goodbye!
INFO:aiogram:Bot: СЛИФФКИ БОТ [@sliffkifans_bot]
INFO:aiogram.dispatcher.dispatcher:Start polling.
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-7' coro=<Dispatcher._process_polling_updates() done, defined at /home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:409> exception=UndefinedColumn('column "sliffki1" does not exist\nLINE 1: UPDATE actual SET link = sliffki1 WHERE id > 0\n                                 ^\n')>
Traceback (most recent call last):
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 417, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 238, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 259, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/nail/oir/actual.py", line 62, in add
    cursor.execute(f'UPDATE actual SET link = {linked} WHERE id > 0')
psycopg2.errors.UndefinedColumn: column "sliffki1" does not exist
LINE 1: UPDATE actual SET link = sliffki1 WHERE id > 0
                                 ^

INFO:root:new luder: 1882355196
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-15' coro=<Dispatcher._process_polling_updates() done, defined at /home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:409> exception=UndefinedColumn('column "sliffki1" does not exist\nLINE 1: UPDATE actual SET link = sliffki1 WHERE id > 0\n                                 ^\n')>
Traceback (most recent call last):
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 417, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 238, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 259, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/nail/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/nail/oir/actual.py", line 62, in add
    cursor.execute(f'UPDATE actual SET link = {linked} WHERE id > 0')
psycopg2.errors.UndefinedColumn: column "sliffki1" does not exist
LINE 1: UPDATE actual SET link = sliffki1 WHERE id > 0
                                 ^

INFO:aiogram.dispatcher.dispatcher:Stop polling...
WARNING:aiogram:Goodbye!
INFO:aiogram:Bot: СЛИФФКИ БОТ [@sliffkifans_bot]
INFO:aiogram.dispatcher.dispatcher:Start polling.
INFO:root:new luder: 1882355196
